const Incharge = [
  {
    _id: "6800ae11293c0f584537a951",
    categoryId: "IN2",
    name: "kamran",
    processeName: "Milling Manual",
    processess: ["MM004"],
    operators: [
      
      {
        name: "Harish Jain",
        categoryId: "O8",
        _id: "68061f5195341dc652464434",
      },
    ],
    __v: 0,
  },
];

const user = [
  {
    _id: "67a8f8ae3bb027aa0c8c3587",
    categoryId: "O1",
    name: "Ajay Singh",
    processName: [
      "CNC Lathe",
      "Milling Manual",
      "Grinding Final",
      "Wire Cut Rough",
      "VMC Local",
      "VMC Imported",
      "Drill/Tap",
    ],
    __v: 37,
    shifts: 200,
    leavePeriod: [
      {
        startDate: "2025-04-17T18:30:00.000Z",
        endDate: "2025-04-18T18:30:00.000Z",
        reason: "testing leave",
        _id: "68028ca9482ca82763cc3541",
      },
    ],
    status: "On Leave",
  },
  {
    _id: "67a9902c887c51680885dddd",
    categoryId: "O2",
    name: "Kamran",
    processName: [
      "Wire Cut Imported",
      "Wire Cut Rough",
      "Drill/Tap",
      "Wire Cut Local",
      "VMC Local",
    ],
    __v: 12,
    shifts: 200,
    leavePeriod: [],
    status: "Active",
  },
  {
    _id: "67aaf6cea312ae30fe6edf46",
    categoryId: "O3",
    name: "Abdul",
    processName: [
      "Black Oxide",
      "Laser Marking",
      "Lapping/Polishing",
      "Grinding Blank/Rough",
      "Gauges & fixtures",
      "Grinding Final",
    ],
    __v: 2,
    shifts: 32,
    leavePeriod: [],
    status: "Active",
  },
  {
    status: "Active",
    _id: "67af9699a04a8812685b61b6",
    categoryId: "O4",
    name: "Rahul Singh",
    processName: ["Cylindrical Grinding", "Manual Lathe", "Hydraulic Grinding"],
    shifts: 12,
    __v: 0,
    leavePeriod: [],
  },
  {
    _id: "67b6cd583c8617d72a52c7df",
    categoryId: "O5",
    name: "Rajesh Kumar",
    processName: ["VMC Local"],
    shifts: 100,
    __v: 2,
    leavePeriod: [],
    status: "Active",
  },
  {
    _id: "67c6f96191b9684bd2e69c56",
    categoryId: "09",
    name: "Vinod Kumar",
    processName: [
      "VMC Imported",
      "VMC Local",
      "CNC Lathe",
      "Wire Cut Local",
      "Grinding Final",
    ],
    __v: 4,
    leavePeriod: [],
    status: "Active",
  },
  {
    status: "Active",
    _id: "67c82454d1ae4c431790bae1",
    categoryId: "06",
    name: "Yash",
    processName: [
      "VMC Imported",
      "VMC Local",
      "CNC Lathe",
      "Wire Cut Imported",
      "Milling Manual",
      "Grinding Final",
      "Wire Cut Rough",
      "Drill/Tap",
      "Wire Cut Local",
      "Black Oxide",
      "Lapping/Polishing",
      "Grinding Blank/Rough",
      "Gauges & fixtures",
      "Laser Marking",
      "Cylindrical Grinding",
      "Manual Lathe",
      "Hydraulic Grinding",
      "TEST",
    ],
    __v: 0,
    leavePeriod: [],
  },
  {
    _id: "67d06ff2321542e5602ef78d",
    categoryId: "07",
    name: "Nandi Sharma",
    processName: [
      "VMC Imported",
      "VMC Local",
      "CNC Lathe",
      "Wire Cut Imported",
      "Milling Manual",
      "Grinding Final",
      "Wire Cut Rough",
      "Drill/Tap",
      "Wire Cut Local",
      "Black Oxide",
      "Lapping/Polishing",
      "Grinding Blank/Rough",
      "Gauges & fixtures",
      "Laser Marking",
      "Cylindrical Grinding",
      "Manual Lathe",
      "Hydraulic Grinding",
    ],
    status: "Active",
    leavePeriod: [
      {
        startDate: "2025-03-21T18:30:00.000Z",
        endDate: "2025-03-21T18:30:00.000Z",
        reason: "hi",
        _id: "67de55fc37a3e1eea37dd9ca",
      },
    ],
    __v: 1,
  },
  {
    _id: "67de7a8f59d7af7315908bad",
    categoryId: "08",
    name: "Pramod Raj",
    processName: ["VMC Imported"],
    status: "Active",
    leavePeriod: [],
    __v: 2,
  },
  {
    _id: "67dfcbbcade7af080a11a545",
    categoryId: "O9",
    name: "Harish Jain",
    processName: [
      "VMC Imported",
      "VMC Local",
      "Milling Manual",
      "Grinding Final",
      "CNC Lathe",
      "Drill/Tap",
      "Wire Cut Local",
      "Wire Cut Rough",
      "Wire Cut Imported",
      "Black Oxide",
      "Laser Marking",
      "Lapping/Polishing",
      "Grinding Blank/Rough",
      "Gauges & fixtures",
      "Cylindrical Grinding",
      "Manual Lathe",
      "Hydraulic Grinding",
      "Testing Mft",
      "TEST-1",
    ],
    status: "Active",
    leavePeriod: [],
    __v: 2,
  },
];

const operatorCategoryIds = Incharge[0].operators.map((op) => op.categoryId);

const filteredUsers = user.filter((u) =>
  operatorCategoryIds.includes(u.categoryId)
);

console.log(filteredUsers);
